### ISSUE TITLE
support RHEL/CentOS

### ISSUE THREAD

**Issue by bngsudheer** [debops/ansible-elasticsearch#7]
I will contribute the code if you like

**Comment by drybjed** [comment]
I'm wary of adding support for different distributions in DebOps, mostly because that makes already long tasks lists in roles even longer, and some part of the code won't be tested (not everything is due to Travis-CI being a limited environment, but that's still Ubuntu, not RH for example).

`debops.elasticsearch` has `debops.etc_services`, `debops.ferm` and `debops.java` Ansible roles as its dependencies. If you would want to use `debops.elasticsearch` on an RH-based system without forking it (even with your RH code included), you would need to add support for RedHat-based OS to these roles as well. And they might have their own role dependencies. And so on, and so on.

So as you can see, doing multiple OSes becomes very tricky very quickly when you consider role dependencies. Alternative is to fork the role, drop dependencies you don't need and add the RH code.

**Comment by bngsudheer** [comment]
Thanks for the detailed response. I think, I will fork it or write a new role for Red Hat based systems.
